import { MaterialWithStatus } from '@/components/dashboard/materials/MaterialDetailsSheet';

export const mockMaterials: MaterialWithStatus[] = [
  {
    id: '1',
    title: 'Cien años de soledad',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1967-06-05',
    status: 'available',
    description: 'Una obra maestra de la literatura latinoamericana',
    authors: [
      {
        id: '1',
        firstName: 'Gabriel',
        middleName: 'García',
        lastName: 'Márquez',
        nationality: 'Colombiano',
        birthDate: '1927-03-06',
      },
    ],
    book: {
      id: 'book-1',
      isbn13: '9780307474728',
      edition: '1era edición',
      numberOfPages: 417,
      materialId: '1',
    },
  },
  {
    id: '2',
    title: 'Don Quijote de la Mancha',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1605-01-16',
    status: 'repair',
    description: 'Clásico de la literatura española',
    authors: [
      {
        id: '2',
        firstName: 'Miguel',
        middleName: 'de',
        lastName: 'Cervantes',
        nationality: 'Español',
        birthDate: '1547-09-29',
      },
    ],
    book: {
      id: 'book-2',
      isbn13: '9788420412146',
      edition: 'Edición de la Real Academia Española',
      numberOfPages: 1200,
      materialId: '2',
    },
  },
  {
    id: '3',
    title: 'La sombra del viento',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '2001-04-17',
    status: 'loaned',
    description: 'Una novela de misterio y romance en la Barcelona de posguerra',
    authors: [
      {
        id: '3',
        firstName: 'Carlos',
        middleName: 'Ruiz',
        lastName: 'Zafón',
        nationality: 'Español',
        birthDate: '1964-09-25',
      },
    ],
    book: {
      id: 'book-3',
      isbn13: '9788408043640',
      edition: '1era edición',
      numberOfPages: 575,
      materialId: '3',
    },
  },
  {
    id: '4',
    title: 'El amor en los tiempos del cólera',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1985-09-05',
    status: 'available',
    description: 'Una historia de amor que trasciende el tiempo',
    authors: [
      {
        id: '1',
        firstName: 'Gabriel',
        middleName: 'García',
        lastName: 'Márquez',
        nationality: 'Colombiano',
        birthDate: '1927-03-06',
      },
    ],
    book: {
      id: 'book-4',
      isbn13: '9780307389732',
      edition: '1era edición',
      numberOfPages: 368,
      materialId: '4',
    },
  },
  {
    id: '5',
    title: 'Rayuela',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1963-06-28',
    status: 'available',
    description: 'Una novela experimental que revolucionó la literatura',
    authors: [
      {
        id: '4',
        firstName: 'Julio',
        middleName: null,
        lastName: 'Cortázar',
        nationality: 'Argentino',
        birthDate: '1914-08-26',
      },
    ],
    book: {
      id: 'book-5',
      isbn13: '9788420471570',
      edition: '1era edición',
      numberOfPages: 600,
      materialId: '5',
    },
  },
  {
    id: '6',
    title: 'Ficciones',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1944-01-01',
    status: 'reserved',
    description: 'Colección de cuentos que desafían la realidad',
    authors: [
      {
        id: '5',
        firstName: 'Jorge',
        middleName: 'Luis',
        lastName: 'Borges',
        nationality: 'Argentino',
        birthDate: '1899-08-24',
      },
    ],
    book: {
      id: 'book-6',
      isbn13: '9788420633114',
      edition: 'Edición especial',
      numberOfPages: 208,
      materialId: '6',
    },
  },
  {
    id: '7',
    title: 'Pedro Páramo',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1955-03-19',
    status: 'available',
    description: 'Una novela sobre la muerte y los recuerdos',
    authors: [
      {
        id: '6',
        firstName: 'Juan',
        middleName: null,
        lastName: 'Rulfo',
        nationality: 'Mexicano',
        birthDate: '1917-05-16',
      },
    ],
    book: {
      id: 'book-7',
      isbn13: '9788437600093',
      edition: '1era edición',
      numberOfPages: 124,
      materialId: '7',
    },
  },
  {
    id: '8',
    title: 'La casa de los espíritus',
    subtitle: null,
    type: 'book',
    language: 'Español',
    publishedDate: '1982-10-12',
    status: 'available',
    description: 'Saga familiar en el contexto de la historia de Chile',
    authors: [
      {
        id: '7',
        firstName: 'Isabel',
        middleName: null,
        lastName: 'Allende',
        nationality: 'Chilena',
        birthDate: '1942-08-02',
      },
    ],
    book: {
      id: 'book-8',
      isbn13: '9788401242267',
      edition: '1era edición',
      numberOfPages: 433,
      materialId: '8',
    },
  },
];
